# In your project directory
echo '[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.139.0"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --enableGitInfo"

[context.deploy-preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"' > netlify.toml